services:
  redis:
    image: redis:7-alpine

  backend:
    build: ./backend
    volumes:
      - ${PROJECTS_PATH:-./projects}:/app/projects
      - ./backend:/app
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=debug
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  projects:
    driver: local
